In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('creditcard.csv')

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

In [5]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

From the above,it is clear that it is an imbalnced dataset.

In [7]:
##Splitting Independent and dependent features
X=df.drop('Class',axis=1)
y=df['Class']

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [9]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [10]:
a=10.0**np.arange(-2,3)
a

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [11]:
lg=LogisticRegression()
grid={'C':a,'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [12]:
clf=GridSearchCV(lg,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [13]:
y_pred=clf.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))    

0.9988764439450862
[[85263    50]
 [   46    84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85313
           1       0.63      0.65      0.64       130

    accuracy                           1.00     85443
   macro avg       0.81      0.82      0.82     85443
weighted avg       1.00      1.00      1.00     85443



In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
classifier=RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [16]:
y_prediction=classifier.predict(x_test)
print(accuracy_score(y_test,y_prediction))
print(confusion_matrix(y_test,y_prediction))
print(classification_report(y_test,y_prediction))    

0.9995552590615966
[[85307     6]
 [   32    98]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85313
           1       0.94      0.75      0.84       130

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [17]:
y_train.value_counts()

0    199002
1       362
Name: Class, dtype: int64

In [18]:
##lets increase the weight of class containing output as '1'
class_weight=dict({0:1,1:100})

In [19]:
clfr=RandomForestClassifier(class_weight=class_weight)
clfr.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [20]:
y_predi=clfr.predict(x_test)
print(confusion_matrix(y_test,y_predi))
print(accuracy_score(y_test,y_predi))
print(classification_report(y_test,y_predi))

[[85308     5]
 [   33    97]]
0.9995552590615966
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85313
           1       0.95      0.75      0.84       130

    accuracy                           1.00     85443
   macro avg       0.98      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443



Random Forest Classifier works well with imbalanced dataset.

# Under sampling---Reduce the points of the maximum labels

In [21]:
y_train.value_counts()

0    199002
1       362
Name: Class, dtype: int64

In [24]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)

In [26]:
x_train_ns,y_train_ns=ns.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199002, 1: 362})
The number of classes after fit Counter({0: 452, 1: 362})


In [28]:
362/0.8

452.5

In [29]:
0.8*452

361.6

In [30]:
rfc=RandomForestClassifier()
rfc.fit(x_train_ns,y_train_ns)

RandomForestClassifier()

In [31]:
Y_pred=rfc.predict(x_test)
print(confusion_matrix(y_test,Y_pred))
print(accuracy_score(y_test,Y_pred))
print(classification_report(y_test,Y_pred))

[[62712 22601]
 [   11   119]]
0.7353557342321781
              precision    recall  f1-score   support

           0       1.00      0.74      0.85     85313
           1       0.01      0.92      0.01       130

    accuracy                           0.74     85443
   macro avg       0.50      0.83      0.43     85443
weighted avg       1.00      0.74      0.85     85443



precision is very very less and also so many errors.

# Over sampling: Increase the points of minimum labels

In [33]:
from imblearn.over_sampling import RandomOverSampler

In [35]:
os=RandomOverSampler(0.75)
x_train_os,y_train_os=os.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_os)))

The number of classes before fit Counter({0: 199002, 1: 362})
The number of classes after fit Counter({0: 199002, 1: 149251})


In [38]:
RFC=RandomForestClassifier()
RFC.fit(x_train_os,y_train_os)

RandomForestClassifier()

In [39]:
pred_y=RFC.predict(x_test)
print(confusion_matrix(y_test,pred_y))
print(accuracy_score(y_test,pred_y))
print(classification_report(y_test,pred_y))

[[85308     5]
 [   29   101]]
0.999602073897218
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85313
           1       0.95      0.78      0.86       130

    accuracy                           1.00     85443
   macro avg       0.98      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



In [40]:
from sklearn.model_selection import cross_val_score

In [42]:
accurate=cross_val_score(RFC,X,y,cv=5)
print(accurate.mean(),accurate.std())

0.8013236833131311 0.3962817688089879


# SMOTETomek

In [43]:
from imblearn.combine import SMOTETomek

In [46]:
smt=SMOTETomek(0.75)
x_train_sm,y_train_sm=smt.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_sm)))

The number of classes before fit Counter({0: 199002, 1: 362})
The number of classes after fit Counter({0: 198286, 1: 148535})


In [47]:
rf=RandomForestClassifier()
rf.fit(x_train_sm,y_train_sm)

RandomForestClassifier()

In [48]:
prediction_y=rf.predict(x_test)
print(confusion_matrix(y_test,prediction_y))
print(accuracy_score(y_test,prediction_y))
print(classification_report(y_test,prediction_y))

[[85298    15]
 [   24   106]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85313
           1       0.88      0.82      0.84       130

    accuracy                           1.00     85443
   macro avg       0.94      0.91      0.92     85443
weighted avg       1.00      1.00      1.00     85443

